### PR TITLE
modifications on getItemRendererByIndex for PageableList

### PR DESCRIPTION
**Pull request by harbalk**
Proposal to fix https://github.com/ibm-js/deliteful/issues/569

### CODE REVIEW

**Comment by wkeese** [comment]
Shouldn't this have a test?   Or are the existing tests already failing?

**Comment by harbalk** [comment]
There was a test but it didn't use the function correctly. (It is the tests modified in the commit).
The test was asking the item at index 0 to get the first item displayed (item 10 in the test) but not the item which is at the first index in the list (item 0).

**Comment by harbalk** [comment]
Reading the description of the function again, I think the question is to know what do we mean by index.
If it is the index in the item displayed (equivalent to the itemRenderers) the old version of the function was correct.
But we shouldn't use it in the function itemRemoved and itemUpdated in List.js, where the index used is the index of the item in the list.

**Comment by cjolif** [comment]
@harbalk is your PR on ObservableArray depending on this one? Or can it work even without this fix?

**Comment by harbalk** [comment]
@cjolif  it can work without this fix.

**Comment by cjolif** [comment]
was that closed by mistake or has the fix been merged? (if yes a link to the commit ID would be nice).

**Comment by harbalk** [comment]
The fix has not been merged. I dig into it again and I realize the problem occured only when it is an itemUpdated. Also the problem was not coming from getItemRendererByIndex but from PageableList which overwrite itemAdded and ItemRemoved but not itemUpdated.
I made the correction on another branch I will do the PR in a few minutes.

**Comment by cjolif** [comment]
ok, next time leave comments when closing so that I don't wonder what's happening ;) thanks.

**Pull request closed without merging**
