### PR TITLE
modif samples : remove register.parse

### PR DESCRIPTION
**Pull request by harbalk**
I made the corrections on a part of the samples as asked in this issue : https://github.com/ibm-js/deliteful/issues/541
I have tested it on Chrome, Firefox, IE11, Safari (on iOS8) and Android (4.X).
I didn't find any regression.
There is however a problem on Android devices with Android browser where any tests is running (but works perfectly on Chrome for Android and Firefox).
Also one little problem on StarRating.html where green-man style doesn't work on Chrome for Android.

### CODE REVIEW

**Comment by edchat** [comment]
Which Android devices, and versions were having problems?

**Comment by harbalk** [comment]
On HTC One M8 4.4 and Samsung Galaxy S4 4.2.2 "Internet" Browser. (Like I said it works with Chrome and Firefox).
But the tests weren't running before the modifications of parse call so I don't think this come from that..

**Comment by cjolif** [comment]
> But the tests weren't running before the modifications of parse call so I don't think this come from that..

When I was asking for possible regressions I was meaning against delite 0.6. Not just after the parse() call removal.

**Comment by wkeese** [comment]
Also, you mentioned that nothing works on IE11 with the latest dcl.  Did you file a ticket for that?

**Comment by harbalk** [comment]
It was EAlexRojas who had the problem with the latest dcl. I don't have the informations.

**Comment by wkeese** [comment]
Oh OK.  The changes to the samples look good.  I assume someone is doing the tests separately.

**Comment by edchat** [comment]
Merged with https://github.com/ibm-js/deliteful/commit/4c678a501b1f85f489d4bc33b51a5beee6dde1b3

**Pull request closed without merging**
