### PR TITLE
Fix Combopopup on mobile

### PR DESCRIPTION
**Pull request by wkeese**
Fix regression in Combobox on mobile where typing into the `<input>` in the Comopopup makes the whole popup close.

Refs #639.

### CODE REVIEW

**Comment by wkeese** [comment]
@brunano21, this definitely fixes the problem, but I found another issue with the original fix for #639...

I tracked down why the `<input>` is cleared, and what's actually happening is that every time you call `closeDropDown()` and `openDropDown()`, the dropdown is being **recreated**`.  It's because `HasDropDown#openDropDown()` calls `Combobox#loadDropDown()`, which unconditionally calls `createCenteredDropDown()`, which creates a new `ComboPopup`.   Seems like it would be better (faster) if we could avoid doing that.  

Looks like desktop doesn't have that problem because although `Combobox#loadDropDown()` unconditionally calls `createAboveBelowDropDown()`, that method simply returns `this.list`.

**Comment by wkeese** [comment]
PS: Another problem with the current design is that the dialog actually jumps around as you type.  But I guess one problem at a time.

**Comment by brunano21** [comment]
@wkeese Ok, I see your point. However I think the original problem of this (closing/opening the popup) is due to the lack of a `redraw()` method in `delite/popup.js`. As matter of fact, we tend to close and open the `dropDown` because we want to recalculate the new `dropDown`'s size when its content changes.
How worth is it to implement a `redraw()` method? is that possible? It would make things much easier _I think_.

**Comment by wkeese** [comment]
Agreed, I'll try to add a `redraw()` method.  Actually I think it's already there in the `_repositionAll()` method so it's just a question of making that or a similar method public.

**Comment by brunano21** [comment]
The `delite/popup#_repositionAll()` isn't accessible, because `delite/HasDropDown` doesn't inherit from `delite/popup`.

**Comment by wkeese** [comment]
Replaced by #648.

**Pull request closed without merging**
